_target_: maxyfold.models.litmodules.pdb_module.PDBLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01 # Use a high LR for overfitting
  weight_decay: 0.0

scheduler: null

loss_fn:
  _target_: maxyfold.models.losses.mse_loss.MSELoss
  weight: 1.0

model:
  _target_: maxyfold.models.architectures.dummy.DummyNet
  crop_size: ${data.cropper.crop_size}

sync_dist: false
log_structure_metrics: true
max_pairwise_tokens: ${data.cropper.crop_size}